apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tuesday-rolebinding
  namespace: tuesday
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: tuesday-role
  apiGroup: rbac.authorization.k8s.io
