apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: tuesday
  labels:
    day: tuesday
    environment: dev
    name: tuesday
    cluster: local
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    contact: Ashik Zebulun
    openshift.io/description: To test Argo CD
    openshift.io/display-name: A namespace called Monday

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: tuesday
  namespace: tuesday
spec:
  hard:
    cpu: "1"
    memory: 1Gi
    pods: "5"


---

apiVersion: v1
kind: LimitRange
metadata:
  name: tuesday
  namespace: tuesday
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 100Mi
  - type: Container
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 100Mi
    defaultRequest:
      cpu: "0.2"
      memory: 200Mi


---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tuesday-role
  namespace: tuesday
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tuesday-rolebinding
  namespace: tuesday
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: tuesday-role
  apiGroup: rbac.authorization.k8s.io
