apiVersion: v1
kind: ResourceQuota
metadata:
  name: monday
  namespace: monday
  annotations:
  argocd.io/sync-wave: "2"
spec:
  hard:
    cpu: "1"
    memory: 1Gi
    pods: "5"


---

apiVersion: v1
kind: LimitRange
metadata:
  name: monday
  namespace: monday
  annotations:
  argocd.io/sync-wave: "2"
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 100Mi
  - type: Container
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 100Mi
    defaultRequest:
      cpu: "0.2"
      memory: 200Mi


---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monday-role
  namespace: monday
  annotations:
  argocd.io/sync-wave: "3"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monday-rolebinding
  namespace: monday
  annotations:
  argocd.io/sync-wave: "4"
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: monday-role
  apiGroup: rbac.authorization.k8s.io
