apiVersion: v1
kind: LimitRange
metadata:
  name: thursday
  namespace: thursday
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 100Mi
  - type: Container
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: "0.1"
      memory: 100Mi
    defaultRequest:
      cpu: "0.2"
      memory: 200Mi
