apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monday-rolebinding
  namespace: monday
  annotations:
  argocd.io/sync-wave: "4"
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: monday-role
  apiGroup: rbac.authorization.k8s.io