apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monday-role
  namespace: monday
  annotations:
  argocd.io/sync-wave: "3"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]