apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: friday-role
  namespace: friday
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
