apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: friday-rolebinding
  namespace: friday
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: friday-role
  apiGroup: rbac.authorization.k8s.io
