apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wednesday-rolebinding
  namespace: wednesday
subjects:
- kind: User
  name: developer
roleRef:
  kind: Role
  name: wednesday-role
  apiGroup: rbac.authorization.k8s.io
